---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install docker engine dependencies"
  become: true
  apt:
    name:
      ["apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release"]
    state: latest
    update_cache: yes

- name: install setfacl support
  become: yes
  apt:
    name: acl

# - name: "add docker dpk key"
#   get_url:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     dest: /tmp
#     mode: "0777"

- name: Add "add docker dpk key."
  become: true
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Setup stable repo for docker"
  become: true
  shell: |
    echo \
     "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "install docker engine "
  become: true
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest
    update_cache: yes

- name: "download Minikube."
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp
    mode: "0777"

- name: Install minikube
  become: true
  shell: |
    install /tmp/minikube-linux-amd64 /usr/local/bin/minikube

- name: Add user
  become: true
  shell: |
    groupadd docker
    usermod -aG docker ubuntu

- name: start minikube cluster
  become: yes
  become_user: ubuntu
  shell: |
    minikube start --driver=docker

- name: "add kuectl dpk key"
  become: true
  shell: |
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: "add kubernetes repo"
  become: true
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: "install kubectl "
  become: true
  apt:
    name: ["kubectl"]
    state: latest
    update_cache: yes
