---
- name: Creates directory
  file:
    path: /home/ubuntu/kube
    state: directory

- name: copy deployment files to ec2 server
  become: yes
  copy:
    src: /root/project/kube
    dest: /home/ubuntu
# - name: Deploy to kubernetes cluster
#   become: yes
#   shell: |
#     cd /home/ubuntu
#     kubectl apply -f kube

# - name: get pods
#   become: yes
#   shell: |
#     kubectl get pods
